version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Cindy says hello"
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Bobby says hello"
  workflows:
    version: 2
    build_and_test: 
      jobs:
        - build
        - test
